### ISSUE TITLE
Use of sys.version_info.major in pyprinttags.py doesn't work in Python 2.6

### ISSUE THREAD

**Issue by alnesbit** [supermihi/pytaglib#4]
Running pyprinttags.py in a Python 2.6 installation fails with the following exception:

```
  File "/home/alnesbit/local/lib/python2.6/site-packages/pytaglib-0.3.5-py2.6-linux-x86_64.egg/pyprinttags.py", line 41, in script
    if sys.version_info.major == 2:
AttributeError: 'tuple' object has no attribute 'major'
```

sys.version_info only became a named tuple in 2.7. To get this to work in 2.6, it needs to be accessed as a regular tuple:

```
if sys.version_info[0] == 2:
```
