### ISSUE TITLE
Build on FreeBSD 10.1 Fails Due to Include Path

### ISSUE THREAD

**Issue by haljhon** [supermihi/pytaglib#11]
I attempted to build/install this on FreeBSD and I noticed that the build fails citing a missing tstring.h:

building 'taglib' extension
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -I/usr/local/include/python2.7 -c src/taglib.cpp -o build/temp.freebsd-10.1-RELEASE-amd64-2.7/src/taglib.o
src/taglib.cpp:352:10: fatal error: 'taglib/tstring.h' file not found
#include "taglib/tstring.h"
         ^
1 error generated.
error: command 'cc' failed with exit status 1

I had to modify the setup.py definition on line 42:

    extensions = [Extension('taglib', [os.path.join('src', 'taglib.cpp')], libraries=['tag'], include_dirs=['/usr/local/include'])]

The includes for taglib are in /usr/local/include on FreeBSD (because taglib is built using ports and most things are put in /usr/local/ on BSD anyway).

**Comment by supermihi** [comment]
Hi haljhon,
first of all, sorry for the late reply, I somehow missed the issue. 

I don't think that this is a bug in pytaglib, as we do not set *any* include paths but rather rely on the (OS-dependent) standard include directories. If `/usr/local/include` is a default location for includes on FreeBSD, you should probably put that directory into the `CPP_INCLUDE_PATH` environment variable. Alternatively, you can compile the package using

    python setup.py build_ext --include-dirs '/usr/local/include'

so you do not have to edit the `setup.py`. I can add this to the README to help other users compiling against non-standard taglib installations.
